#! /bin/bash

BASE=/usr/lib/avnav/raspberry/network-nm
cmd=firewall-offline-cmd
if systemctl --quiet is-active firewalld ; then
  cmd=firewall-cmd
fi
current="`$cmd --get-default-zone`"
if [ "$current" != "trusted" ] ; then
  echo "current default zone is $current"
  echo "setting default zone for firewalld to trusted with $cmd"
  $cmd --set-default-zone trusted
else
  echo "firewall default zone already trusted"
fi
for f in 73-usb-net-by-mac.link 99-default.link
do
  fn=/etc/systemd/network/$f
  if [ -e $fn ] ; then
    echo "removing $fn"
    rm -f "$fn"
  else
    echo "$fn already removed"
  fi
done
"$BASE/set-network.py" -i

