// This file was autogenerated by ../libraries/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../viewer/avnav_viewer.js', ['avnav.main'], ['avnav.gui.Handler', 'ol.Map']);
goog.addDependency('../../../../viewer/gui/handler.js', ['avnav.gui.Handler'], ['avnav.gui.Mainpage', 'avnav.gui.Statuspage']);
goog.addDependency('../../../../viewer/gui/mainpage.js', ['avnav.gui.Mainpage'], ['avnav.gui.Handler', 'avnav.gui.Page']);
goog.addDependency('../../../../viewer/gui/page.js', ['avnav.gui.Page'], ['avnav.gui.Handler']);
goog.addDependency('../../../../viewer/gui/statuspage.js', ['avnav.gui.Statuspage'], ['avnav.gui.Handler', 'avnav.gui.Page']);
