// This file was autogenerated by D:\Users\Andreas\Documents\GitHub\avnav\libraries\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../../viewer/avnav_viewer.js', ['avnav.main'], ['avnav.gui.Handler', 'avnav.gui.Mainpage', 'avnav.gui.Navpage', 'avnav.gui.Statuspage', 'avnav.map.MapHolder', 'avnav.nav.NavObject', 'avnav.util.PropertyHandler']);
goog.addDependency('../../../../viewer/gui/handler.js', ['avnav.gui.Handler', 'avnav.gui.PageEvent'], ['avnav.nav.NavObject']);
goog.addDependency('../../../../viewer/gui/mainpage.js', ['avnav.gui.Mainpage'], ['avnav.gui.Handler', 'avnav.gui.Page', 'goog.object']);
goog.addDependency('../../../../viewer/gui/navpage.js', ['avnav.gui.Navpage'], ['avnav.gui.Handler', 'avnav.gui.Page']);
goog.addDependency('../../../../viewer/gui/page.js', ['avnav.gui.Page'], ['avnav.gui.Handler', 'goog.asserts']);
goog.addDependency('../../../../viewer/gui/statuspage.js', ['avnav.gui.Statuspage'], ['avnav.gui.Handler', 'avnav.gui.Page']);
goog.addDependency('../../../../viewer/map/mapholder.js', ['avnav.map.MapHolder'], []);
goog.addDependency('../../../../viewer/nav/gpsdata.js', ['avnav.nav.GpsData'], ['avnav.util.Formatter', 'avnav.util.PropertyHandler', 'avnav.util.geo.GpsInfo', 'goog.date.Date', 'goog.date.DateTime']);
goog.addDependency('../../../../viewer/nav/navobject.js', ['avnav.nav.NavEvent', 'avnav.nav.NavObject'], ['avnav.nav.GpsData', 'avnav.util.GeoCompute', 'avnav.util.geo.Distance', 'avnav.util.geo.GpsInfo', 'avnav.util.geo.Point']);
goog.addDependency('../../../../viewer/util/formatter.js', ['avnav.util.Formatter'], ['avnav.util.geo.Point']);
goog.addDependency('../../../../viewer/util/geo.js', ['avnav.util.geo.Cpa', 'avnav.util.geo.Distance', 'avnav.util.geo.GpsInfo', 'avnav.util.geo.Point'], []);
goog.addDependency('../../../../viewer/util/geocompute.js', ['avnav.util.GeoCompute'], ['avnav.util.geo.Cpa', 'avnav.util.geo.Distance', 'avnav.util.geo.GpsInfo', 'avnav.util.geo.Point']);
goog.addDependency('../../../../viewer/util/propertyhandler.js', ['avnav.util.PropertyHandler'], ['goog.object']);
