#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Fri Nov  7 18:47:34 2014

import wx

# begin wxGlade: extracode
# end wxGlade


class Avnav(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Avnav.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.button_4 = wx.Button(self, -1, "SelectFile")
        self.startServer = wx.CheckBox(self, -1, "auto start server")
        self.serverPid = wx.StaticText(self, -1, "server stopped", style=wx.ALIGN_CENTRE)
        self.btStartServer = wx.Button(self, -1, "Start Server")
        self.button_3 = wx.Button(self, -1, "button_3")
        self.button_2 = wx.Button(self, -1, "button_2")
        self.button_1 = wx.Button(self, -1, "Exit")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.selectFileClick, self.button_4)
        self.Bind(wx.EVT_BUTTON, self.buttonExitClicked, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Avnav.__set_properties
        self.SetTitle("frame_1")
        self.SetSize((934, 497))
        self.text_ctrl_1.SetBackgroundColour(wx.Colour(255, 247, 69))
        self.serverPid.SetBackgroundColour(wx.Colour(112, 219, 147))
        self.serverPid.SetForegroundColour(wx.Colour(255, 0, 0))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Avnav.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.text_ctrl_1, 4, wx.EXPAND, 0)
        sizer_4.Add(self.button_4, 0, wx.RIGHT | wx.ALIGN_RIGHT, 5)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 10, wx.EXPAND, 0)
        sizer_5.Add(self.startServer, 3, wx.EXPAND, 0)
        sizer_5.Add(self.serverPid, 10, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL | wx.SHAPED, 3)
        sizer_5.Add(self.btStartServer, 2, 0, 0)
        sizer_1.Add(sizer_5, 1, wx.ALL | wx.EXPAND, 1)
        sizer_2.Add(self.button_3, 0, wx.ALIGN_RIGHT, 0)
        sizer_2.Add(self.button_2, 0, wx.ALIGN_RIGHT, 0)
        sizer_2.Add(self.button_1, 0, wx.LEFT | wx.ALIGN_RIGHT, 30)
        sizer_1.Add(sizer_2, 0, wx.ALL | wx.ALIGN_RIGHT, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def selectFileClick(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler `selectFileClick' not implemented!"
        event.Skip()

    def buttonExitClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler `buttonExitClicked' not implemented!"
        event.Skip()

# end of class Avnav
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = Avnav(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
