#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade not found on Mon Nov 10 09:46:54 2014
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Avnav(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Avnav.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.inputFiles = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.btSelectInput = wx.Button(self, wx.ID_ANY, "SelectFile")
        self.btEmpty = wx.Button(self, wx.ID_ANY, "Empty")
        self.label_2 = wx.StaticText(self, wx.ID_ANY, "OutputDir")
        self.outputDir = wx.TextCtrl(self, wx.ID_ANY, "")
        self.btSelectOut = wx.Button(self, wx.ID_ANY, "Change")
        self.btOutDefault = wx.Button(self, wx.ID_ANY, "Default")
        self.updateMode = wx.CheckBox(self, wx.ID_ANY, "update mode")
        self.label_1 = wx.StaticText(self, wx.ID_ANY, "")
        self.btStart = wx.Button(self, wx.ID_ANY, "Start")
        self.static_line_2 = wx.StaticLine(self, wx.ID_ANY)
        self.startServer = wx.CheckBox(self, wx.ID_ANY, "auto start server")
        self.serverPid = wx.StaticText(self, wx.ID_ANY, "server stopped", style=wx.ALIGN_CENTER)
        self.btStartServer = wx.Button(self, wx.ID_ANY, "Start Server")
        self.static_line_3 = wx.StaticLine(self, wx.ID_ANY)
        self.btExit = wx.Button(self, wx.ID_ANY, "Exit")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btSelectInputClicked, self.btSelectInput)
        self.Bind(wx.EVT_BUTTON, self.btEmptyClicked, self.btEmpty)
        self.Bind(wx.EVT_BUTTON, self.btSelectOutClicked, self.btSelectOut)
        self.Bind(wx.EVT_BUTTON, self.btOutDefaultClicked, self.btOutDefault)
        self.Bind(wx.EVT_BUTTON, self.btStartClicked, self.btStart)
        self.Bind(wx.EVT_BUTTON, self.btStartServerClicked, self.btStartServer)
        self.Bind(wx.EVT_BUTTON, self.btExitClicked, self.btExit)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Avnav.__set_properties
        self.SetTitle("Avnav")
        self.SetSize((934, 497))
        self.inputFiles.SetBackgroundColour(wx.Colour(255, 247, 69))
        self.serverPid.SetBackgroundColour(wx.Colour(112, 219, 147))
        self.serverPid.SetForegroundColour(wx.Colour(255, 0, 0))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Avnav.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.inputFiles, 4, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 7)
        sizer_4.Add(self.btSelectInput, 0, wx.ALIGN_RIGHT | wx.RIGHT, 5)
        sizer_4.Add(self.btEmpty, 0, wx.ALIGN_RIGHT | wx.ALL, 5)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 10, wx.EXPAND, 0)
        sizer_7.Add(self.label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 3)
        sizer_7.Add(self.outputDir, 2, wx.EXPAND, 0)
        sizer_7.Add(self.btSelectOut, 0, wx.LEFT | wx.RIGHT, 5)
        sizer_7.Add(self.btOutDefault, 0, wx.LEFT | wx.RIGHT, 5)
        sizer_1.Add(sizer_7, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)
        sizer_6.Add(self.updateMode, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 8)
        sizer_6.Add(self.label_1, 1, wx.ALIGN_RIGHT | wx.EXPAND, 0)
        sizer_6.Add(self.btStart, 0, wx.ALIGN_RIGHT, 0)
        sizer_1.Add(sizer_6, 0, wx.ALL | wx.EXPAND, 5)
        sizer_1.Add(self.static_line_2, 0, wx.EXPAND, 0)
        sizer_5.Add(self.startServer, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND | wx.LEFT, 8)
        sizer_5.Add(self.serverPid, 1, wx.ALL | wx.EXPAND, 3)
        sizer_5.Add(self.btStartServer, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_5, 0, wx.ALL | wx.EXPAND, 5)
        sizer_1.Add(self.static_line_3, 0, wx.EXPAND, 0)
        sizer_2.Add(self.btExit, 0, wx.ALIGN_RIGHT | wx.LEFT, 30)
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 5)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def btSelectInputClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler 'btSelectInputClicked' not implemented!"
        event.Skip()

    def btEmptyClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler 'btEmptyClicked' not implemented!"
        event.Skip()

    def btSelectOutClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler 'btSelectOutClicked' not implemented!"
        event.Skip()

    def btOutDefaultClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler 'btOutDefaultClicked' not implemented!"
        event.Skip()

    def btStartClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler 'btStartClicked' not implemented!"
        event.Skip()

    def btStartServerClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler 'btStartServerClicked' not implemented!"
        event.Skip()

    def btExitClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler 'btExitClicked' not implemented!"
        event.Skip()

# end of class Avnav
