#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Fri Nov  7 18:47:34 2014

import wx

# begin wxGlade: extracode
# end wxGlade


class Avnav(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Avnav.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.inputFiles = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.btSelectInput = wx.Button(self, -1, "SelectFile")
        self.btEmpty = wx.Button(self, -1, "Empty")
        self.label_2 = wx.StaticText(self, -1, "OutputDir")
        self.outputDir = wx.TextCtrl(self, -1, "")
        self.btSelectOut = wx.Button(self, -1, "Change")
        self.btOutDefault = wx.Button(self, -1, "Default")
        self.updateMode = wx.CheckBox(self, -1, "update mode")
        self.label_1 = wx.StaticText(self, -1, "")
        self.btStart = wx.Button(self, -1, "Start")
        self.static_line_2 = wx.StaticLine(self, -1)
        self.startServer = wx.CheckBox(self, -1, "auto start server")
        self.serverPid = wx.StaticText(self, -1, "server stopped", style=wx.ALIGN_CENTRE)
        self.btStartServer = wx.Button(self, -1, "Start Server")
        self.static_line_3 = wx.StaticLine(self, -1)
        self.btExit = wx.Button(self, -1, "Exit")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btSelectInputClicked, self.btSelectInput)
        self.Bind(wx.EVT_BUTTON, self.btEmptyClicked, self.btEmpty)
        self.Bind(wx.EVT_BUTTON, self.btSelectOutClicked, self.btSelectOut)
        self.Bind(wx.EVT_BUTTON, self.btOutDefaultClicked, self.btOutDefault)
        self.Bind(wx.EVT_BUTTON, self.btStartClicked, self.btStart)
        self.Bind(wx.EVT_BUTTON, self.btStartServerClicked, self.btStartServer)
        self.Bind(wx.EVT_BUTTON, self.btExitClicked, self.btExit)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Avnav.__set_properties
        self.SetTitle("Avnav")
        self.SetSize((934, 497))
        self.inputFiles.SetBackgroundColour(wx.Colour(255, 247, 69))
        self.serverPid.SetBackgroundColour(wx.Colour(112, 219, 147))
        self.serverPid.SetForegroundColour(wx.Colour(255, 0, 0))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Avnav.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.inputFiles, 4, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 7)
        sizer_4.Add(self.btSelectInput, 0, wx.RIGHT | wx.ALIGN_RIGHT, 5)
        sizer_4.Add(self.btEmpty, 0, wx.ALL | wx.ALIGN_RIGHT, 5)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 10, wx.EXPAND, 0)
        sizer_7.Add(self.label_2, 0, wx.LEFT | wx.RIGHT | wx.ALIGN_CENTER_VERTICAL, 3)
        sizer_7.Add(self.outputDir, 2, wx.EXPAND, 0)
        sizer_7.Add(self.btSelectOut, 0, wx.LEFT | wx.RIGHT, 5)
        sizer_7.Add(self.btOutDefault, 0, wx.LEFT | wx.RIGHT, 5)
        sizer_1.Add(sizer_7, 0, wx.TOP | wx.BOTTOM | wx.EXPAND, 5)
        sizer_6.Add(self.updateMode, 0, wx.LEFT | wx.ALIGN_CENTER_VERTICAL, 8)
        sizer_6.Add(self.label_1, 1, wx.EXPAND | wx.ALIGN_RIGHT, 0)
        sizer_6.Add(self.btStart, 0, wx.ALIGN_RIGHT, 0)
        sizer_1.Add(sizer_6, 0, wx.ALL | wx.EXPAND, 5)
        sizer_1.Add(self.static_line_2, 0, wx.EXPAND, 0)
        sizer_5.Add(self.startServer, 0, wx.LEFT | wx.EXPAND | wx.ALIGN_CENTER_VERTICAL, 8)
        sizer_5.Add(self.serverPid, 10, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL | wx.SHAPED, 3)
        sizer_5.Add(self.btStartServer, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_5, 0, wx.ALL | wx.EXPAND, 5)
        sizer_1.Add(self.static_line_3, 0, wx.EXPAND, 0)
        sizer_2.Add(self.btExit, 0, wx.LEFT | wx.ALIGN_RIGHT, 30)
        sizer_1.Add(sizer_2, 0, wx.ALL | wx.ALIGN_RIGHT, 5)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade



    def buttonExitClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler `buttonExitClicked' not implemented!"
        event.Skip()

    def btEmptyClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler `btEmptyClicked' not implemented"
        event.Skip()

    def btSelectOutClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler `btSelectOutClicked' not implemented"
        event.Skip()

    def btOutDefaultClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler `btOutDefaultClicked' not implemented"
        event.Skip()

    def btStartServerClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler `btStartServerClicked' not implemented"
        event.Skip()

    def btExitClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler `btExitClicked' not implemented"
        event.Skip()

    def btSelectInputClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler `btSelectInputClicked' not implemented"
        event.Skip()

    def btStartClicked(self, event):  # wxGlade: Avnav.<event_handler>
        print "Event handler `btStartClicked' not implemented"
        event.Skip()

# end of class Avnav
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = Avnav(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
