# Dockerfile

# Stage 1: Build - includes compilers and dev tools
FROM python:3.12-slim AS runtime
RUN apt-get update && apt-get install -y git

WORKDIR /app/newDoc


# Create virtual environment in a known location
# This makes it easy to copy to the runtime stage
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install Python dependencies into the virtual environment
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Security: Create non-root user and switch to it
RUN useradd --create-home --shell /bin/bash app \
    && chown -R app:app /app
USER app

EXPOSE 8000

# Run with gunicorn for production
CMD ["mkdocs", "serve","--dev-addr","0.0.0.0:8000"]