#! /bin/sh
### BEGIN INIT INFO
# Provides:          check_parts
# Required-Start:    $remote_fs $syslog $network
# Should-Start:      bluetooth dbus udev
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: AV nav server partition enabling
# Description:       creates data partition and mounts
### END INIT INFO

# Author: Andreas Vogel <andreas@wellenvogel.net>

###############################################################################
# Copyright (c) 2012,2013 Andreas Vogel andreas@wellenvogel.net
#
#  Permission is hereby granted, free of charge, to any person obtaining a
#  copy of this software and associated documentation files (the "Software"),
#  to deal in the Software without restriction, including without limitation
#  the rights to use, copy, modify, merge, publish, distribute, sublicense,
#  and/or sell copies of the Software, and to permit persons to whom the
#  Software is furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included
#  in all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#  DEALINGS IN THE SOFTWARE.
###############################################################################
PATH=/sbin:/usr/sbin:/bin:/usr/bin
#set -x

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

NAME=`basename $0`
CONFIG=/etc/default/$NAME

case "$1" in
  start)
  		if [ -f $CONFIG ]; then
  			log_daemon_msg "$CONFIG already exists, do not run again"
  		fi
        log_daemon_msg "Starting background $NAME"
        /etc/init.d/check_parts workersilent &
        log_end_msg 0
        exit 0
        ;;
  workersilent)
  		nostdout=1
  		;;
  worker)
        ;;
  *)
        log_daemon_msg "we only have an action on start"
        log_end_msg 0
        exit 0
        ;;
esac



#check the partitioning of the PI
#we expect the image to have 2 partitions - one for boot and one for the system
#we create a data partition that fills the rest of the SD card
#code was inspired by http://sirlagz.net/category/raspberry-pi/
DEVICE=/dev/mmcblk0
PARTED=/sbin/parted
BASE=/home/pi/avnav
PARTITION=${DEVICE}p3
MOUNTPOINT=/data
ROOTDIR=$MOUNTPOINT/avnav

err(){
  [ "$nostdout" != "1" ] && echo "ERROR: $*"
  logger -t avnav "ERROR: $*"
  exit 1
}
wlog(){
  [ "$nostdout" != "1" ] &&  echo "INFO: $*"
  logger -t avnav "INFO: $*"
}

wlog "avnav partition check started"
[ -x $PARTED ] || err $PARTED not found

quiteflag=""
[ "$nostdout" = "1" ] && quiteflag="-q"
#1.check if the partition is already there
check=`$PARTED -m $DEVICE unit B print | grep '^3:'`
if [ "$check" != "" ] ; then
  wlog "$DEVICE already has 3 partitions"
else
  #2. determine free space
  wlog "going to create 3rd partition on $DEVICE"
  partstart=`$PARTED -m $DEVICE unit B print | grep '^2:'| awk -F: ' { gsub("B$","",$3); print $3 } '`
  partend=`$PARTED -m $DEVICE unit B print | grep "^$DEVICE"| awk -F: ' { gsub("B$","",$2); print $2; } '`
  [ "$partstart" = "" -o "$partend" = "" ] && err "cannot determine start and end for new partition"
  partstart=` echo "$partstart + 1" | bc`
  partend=` echo "$partend - 1" | bc`
  wlog "going to create a partition from $partstart to $partend"
  $PARTED -m -a optimal $DEVICE unit B mkpart primary $partstart $partend < /dev/null|| err "creating partition failed"
  wlog "creating filesystem on $PARTITION"
  mke2fs -t ext4  -i 4096 -b 2048 $quiteflag $PARTITION < /dev/null|| err "creating FS on $PARTITION failed"
fi
#3. check if necessary directories are there
if [ ! -d $MOUNTPOINT ] ; then
  wlog "creating $MOUNTPOINT"
  mkdir -p $MOUNTPOINT || err "unable to create mountpoint"
fi
check=`mount | grep $PARTITION`
if [ "$check" != "" ] ; then
  wlog "$PARTITION already mounted"
else
  mount $PARTITION $MOUNTPOINT || err "unable to mount $PARTITION to $MOUNTPOINT"
fi
if [ ! -d $ROOTDIR ]; then
  mkdir -p $ROOTDIR || err "unable to create $ROOTDIR"
fi
chown pi:pi $ROOTDIR
chmod 755 $ROOTDIR
if [ ! -d $BASE/data ] ; then
  wlog "creating $BASE/data"
  mkdir -p $BASE/data
  chown pi:pi $BASE/data
  chmod 755 $BASE/data
fi
for d in log tracks charts routes import work
do
  if [ ! -d $ROOTDIR/$d ] ; then
    wlog "creating $ROOTDIR/$d"
    mkdir -p $ROOTDIR/$d || err "unable to create $ROOTDIR/$d"
    chown pi:pi $ROOTDIR/$d
    chmod 755 $ROOTDIR/$d
  fi
  if [ ! -h $BASE/data/$d ] ; then
    if [ -d $BASE/data/$d ] ; then
      wlog copying files from $BASE/$d to $ROOTDIR/$d
      cp -r -p $BASE/data/$d/* $ROOTDIR/$d || wlog "copy data from $BASE/data/$d to $ROOTDIR/$d failed"
      rm -rf $BASE/data/$d
    else
  	  [ -e $BASE/data/$d ] && rm -f $BASE/data/$d
  	fi
  	ln -s $ROOTDIR/$d $BASE/data/$d
  fi
done

#4. check fstab
check=`grep "^ *$PARTITION" /etc/fstab`
if [ "$check" != "" ] ; then
  wlog "mountpoint for $PARTITION already found in fstab"
else
  wlog "creating mountpoint for $PARTITION to $MOUNTPOINT in fstab"
  echo "$PARTITION  $MOUNTPOINT           ext4    defaults,noatime,nodiratime  0       1" >> /etc/fstab
fi

wlog "avnav partition setup finished"

echo "#run already finished" > $CONFIG




