#! /bin/sh
#small wrapper around hostapd
HOSTAPD=/usr/sbin/hostapd
HOSTAPD_EDI=/usr/sbin/hostapd.edimax
prfx="avnav-hostapd"
if [ $# != 3 ] ; then
    logger -t $prfx "ERROR: invalid number of parameters, 3 expected"
    exit 1
fi
net=$1
logger -t $prfx "avnav hostapd wrapper started for interface $net"
if [ ! -e /sys/class/net/$net ]; then
  logger -t $prfx "ERROR: network interface $net not found, cannot start hostapd"
  exit 1
fi
drv=`cat /sys/class/net/$net/device/uevent | grep DRIVER `
hasrtl=`echo $drv | grep rtl81`
logger -t $prfx "detected driver $drv"
if [ "$hasrtl" != "" ] ; then
    logger -t $prfx "rtl81xx driver detected"
    if [ -x $HOSTAPD_EDI ] ; then
        logger -t $prfx "using $HOSTAPD.EDI"
        tmpf=/etc/hostapd/$net.edi.conf
        rm -f $tmpf
        sed -e 's/.*driver *=.*/driver=rtl871xdrv/' -e "s/.*interface *=.*/interface=$net/" $3 > $tmpf
        $HOSTAPD_EDI -B -P $2 $tmpf
        exit $?
    else
        logger -t $prfx "$HOSTAPD_EDI not found, starting normal hostapd"
    fi
fi
tmpf=/etc/hostapd/$net.conf
rm -f $tmpf
sed "s/.*interface *=.*/interface=$net/" $3 > $tmpf
logger -t "starting normal hostapd"
$HOSTAPD -B -P $2 $tmpf

